name: IaC Terraform

on:
  workflow_dispatch:
  #push:
    #branches:
    # - develop
    #paths-ignore: [ '.github/**', '.gitignore' ]
    #paths:
    #  - 'environments/dev/**'
#env:
#  PROJECT: ${{ github.event.repository.name }}
#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CAPP_DEV }}
#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CAPP_DEV }}
#  AWS_REGION: ${{ secrets.AWS_REGION }}  


jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Copia repositorio
        uses: actions/checkout@v2
        with:
          ref: develop

  Despliegue_Terraform:
    runs-on: self-hosted
    needs: clean
    #if: contains(github.event.head_commit.message, 'lambda-dev')

    steps:

      - name: Terraform Install
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get install terraform

      #- name: Configurando credenciales para AWS
      #  uses: aws-actions/configure-aws-credentials@v2
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CAPP_DEV }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CAPP_DEV }}
      #    aws-region: ${{ secrets.AWS_REGION }}

      #- name: Sleep for 5 seconds
      #  run: sleep 5s
      #  shell: bash

      - name: Terraform Init
        #env:
        #  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CAPP_DEV }}
        #  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CAPP_DEV }}
        working-directory: ./environments/dev
        run: |
            terraform init -input=false
    
        # Generates an execution plan for Terraform
      #- name: Terraform Plan
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CAPP_DEV }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CAPP_DEV }}
      #  working-directory: ./environments/dev
      #  run: terraform plan -input=false -out="main.tfplan"

      #- name: Terraform Apply
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CAPP_DEV }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CAPP_DEV }}
      #  working-directory: ./environments/dev
      #  run: terraform apply -auto-approve "main.tfplan"